/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.22).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ItemPrice;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-12-28T04:05:37.422Z")

@Validated
@Api(value = "price", description = "the price API")
@RequestMapping(value = "/ep85/spot-hero/1.0.0")
public interface PriceApi {

    @ApiOperation(value = "Get price at a given start and end time", nickname = "getPrice", notes = "It allows the user to request the price for a requested time", response = ItemPrice.class, tags={ "Price", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Price Fetched", response = ItemPrice.class),
        @ApiResponse(code = 400, message = "Unavailable Rates can not span multiple days") })
    @RequestMapping(value = "/price",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ItemPrice> getPrice(@ApiParam(value = "input date/times as ISO-8601 with timezones") @Valid @RequestParam(value = "start", required = false) String start,@ApiParam(value = "input date/times as ISO-8601 with timezones") @Valid @RequestParam(value = "end", required = false) String end);

}
